/*
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
*/

/**
 * @param {string} s
 * @param {string} t
 * @return {character}
 */
var findTheDifference = function(s, t) {
    var nstr = s+t;
    var sarr = nstr.split('').sort();
    for( var i=0, len = sarr.length;i<len;i=i+2 ){
        if( sarr[i] !== sarr[i+1] ){
            return sarr[i];
        }
    }
    return sarr[len-1];
};

var findTheDifference = function(s, t) {
    var lookup = new Map();
    for( char of s ){
        if( lookup.has( char ) ){
            lookup.set( char, lookup.get(char)+1 );
        }
        else{
            lookup.set( char, 1 );
        }
    }
    for( nchar of t ){
        if( !lookup.has( nchar ) ){
            return nchar;
        }
        else{
            var count = lookup.get(nchar) - 1;
            if( count < 0 ){
                return nchar;
            }
            else{
                lookup.set( nchar, lookup.get(nchar)-1 );
            }
        }
    }
    return "";
};

//tags: Google

